# Generated by Django 4.2.1 on 2023-05-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategory',
            name='slug',
            field=models.SlugField(default='qL6R3Fbm', max_length=255, verbose_name='Slug/URL'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='0VZyH4yQ', max_length=255, verbose_name='Slug/URL'),
        ),
    ]
