# Generated by Django 4.2.1 on 2023-05-14 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategory',
            name='slug',
            field=models.SlugField(default='zwNi0REF', max_length=255, verbose_name='Slug/URL'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='772VU0oh', max_length=255, verbose_name='Slug/URL'),
        ),
    ]
